version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - "./myinit.sql:/docker-entrypoint-initdb.d/myinit.sql"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
